trigger:
  branches: 
    include:
    - master
  paths:
    include:
    - src/**

jobs:
- job: ASPNETCore
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '7.0.x'

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: '**/*.sln'
      arguments: '--configuration Release -p:SourceRevisionId=$(Build.SourceVersion)'

  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration Release -p:SourceRevisionId=$(Build.SourceVersion) --no-build --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
    displayName: Copy to Drop
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'Drop'

  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'Nutzungsbasierte Bezahlung (7872a12f-66bb-46b3-8b12-edfaa181e48c)'
      appType: 'webAppContainer'
      WebAppName: 'mannsblog'
      DockerNamespace: 'https://index.docker.io/v1'
      DockerRepository: 'saigkill0/'
      DockerImageTag: 'moonglade-saigkill:latest'