// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

using Microsoft.EntityFrameworkCore;

using Moonglade.Data.Entities;

namespace Moonglade.Data;

public partial class moongladedb722Context : DbContext
{
	public moongladedb722Context(DbContextOptions<moongladedb722Context> options)
		: base(options)
	{
	}

	public virtual DbSet<CertificateEntity> Certificates { get; set; }

	public virtual DbSet<HonoraryPositonEntity> HonoraryPositons { get; set; }

	public virtual DbSet<MandateEntity> Mandates { get; set; }

	public virtual DbSet<MembershipEntity> Memberships { get; set; }

	public virtual DbSet<ProjectEntity> Projects { get; set; }

	public virtual DbSet<PublicationEntity> Publications { get; set; }

	public virtual DbSet<TalkEntity> Talks { get; set; }

	public virtual DbSet<TestimonialEntity> Testimonials { get; set; }

	public virtual DbSet<VideoEntity> Videos { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<CertificateEntity>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK_Certificates_Id");

			entity.ToTable(tb => tb.HasComment("Table for my certificates"));

			entity.Property(e => e.CertificateTite)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Content)
				.IsRequired()
				.HasMaxLength(300)
				.IsUnicode(false);
			entity.Property(e => e.Image)
				.IsRequired()
				.HasMaxLength(300)
				.IsUnicode(false);
			entity.Property(e => e.Language)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Link)
				.IsRequired()
				.HasMaxLength(300)
				.IsUnicode(false);
			entity.Property(e => e.Provider)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Year)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
		});

		modelBuilder.Entity<HonoraryPositonEntity>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK_HonoraryPositons_Id");

			entity.ToTable(tb => tb.HasComment("Table for our Honorary Positions"));

			entity.Property(e => e.Language)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Link)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Organization)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.Summary)
				.HasMaxLength(200)
				.IsUnicode(false);
		});

		modelBuilder.Entity<MandateEntity>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK_Mandates_Id");

			entity.ToTable(tb => tb.HasComment("My Mandates"));

			entity.Property(e => e.Language)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Link)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Organization)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Summary)
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Years)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
		});

		modelBuilder.Entity<MembershipEntity>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK_Memberships_Id");

			entity.ToTable(tb => tb.HasComment("Table for Memberships"));

			entity.Property(e => e.Language)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Link)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.Organzation)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Summary)
				.IsRequired()
				.HasMaxLength(200)
				.IsUnicode(false);
		});

		modelBuilder.Entity<ProjectEntity>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK_Projects_Id");

			entity.ToTable(tb => tb.HasComment("Table with my Projects"));

			entity.Property(e => e.Authors)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Client)
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Completion).HasColumnType("datetime");
			entity.Property(e => e.Language)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.PortfolioLink)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.ProjectLink)
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.ProjectName)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.ProjectSummary)
				.IsRequired()
				.HasMaxLength(200)
				.IsUnicode(false);
			entity.Property(e => e.ProjectType)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
		});

		modelBuilder.Entity<PublicationEntity>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK_Publications_Id");

			entity.ToTable(tb => tb.HasComment("My Publications"));

			entity.Property(e => e.Authors)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.DatePublished).HasColumnType("datetime");
			entity.Property(e => e.Identifier)
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Language)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Link)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.PublicationName)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);
			entity.Property(e => e.Publisher)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Title)
				.IsRequired()
				.HasMaxLength(100)
				.IsUnicode(false);
		});

		modelBuilder.Entity<TalkEntity>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK_Talks_Id");

			entity.ToTable(tb => tb.HasComment("Table of my held talks"));

			entity.Property(e => e.Date).HasColumnType("datetime");
			entity.Property(e => e.Language)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Link)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Summary)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.TalkType)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Title)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Where)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
		});

		modelBuilder.Entity<TestimonialEntity>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK_Testimonials_Id");

			entity.ToTable(tb => tb.HasComment("My Testimonials"));

			entity.Property(e => e.Date).HasColumnType("datetime");
			entity.Property(e => e.ImagePath)
				.IsRequired()
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Language)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Link)
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Recommender)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.RecommenderJob)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.RecommenderLocation)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Relationship)
				.IsRequired()
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Summary)
				.IsRequired()
				.HasMaxLength(600)
				.IsUnicode(false);
		});

		modelBuilder.Entity<VideoEntity>(entity =>
		{
			entity.HasKey(e => e.Id).HasName("PK_Videos_Id");

			entity.ToTable(tb => tb.HasComment("Table of my Videos"));

			entity.Property(e => e.DatePublished).HasColumnType("datetime");
			entity.Property(e => e.Description)
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.Language)
				.HasMaxLength(50)
				.IsUnicode(false);
			entity.Property(e => e.Title)
				.HasMaxLength(150)
				.IsUnicode(false);
			entity.Property(e => e.VideoCode)
				.HasMaxLength(20)
				.IsUnicode(false);
			entity.Property(e => e.VideoType)
				.HasMaxLength(20)
				.IsUnicode(false);
		});

		OnModelCreatingPartial(modelBuilder);
	}

	partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
