// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Moonglade.Data.Entities;

/// <summary>
/// Public Calendar
/// </summary>
[Table("Calendar")]
public partial class CalendarEntity
{
    [Key]
    public int Id { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string EventName { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EventDate { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string Logo { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string Link { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Location { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Note { get; set; }

    public int? Length { get; set; }

    public bool? ReverseLogo { get; set; }
}