// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.EntityFrameworkCore;

using Moonglade.Utils;

namespace Moonglade.Data.Entities;

/// <summary>
/// Table for my certificates
/// </summary>
public partial class CertificateEntity
{
	[Key]
	public int Id { get; set; }

	[Required]
	[StringLength(150)]
	[Unicode(false)]
	public string Provider { get; set; }

	[Required]
	[StringLength(150)]
	[Unicode(false)]
	public string CertificateTite { get; set; }

	[Required]
	[StringLength(50)]
	[Unicode(false)]
	public string Year { get; set; }

	[Required]
	[StringLength(300)]
	[Unicode(false)]
	public string Content { get; set; }

	[Required]
	[StringLength(300)]
	[Unicode(false)]
	public string Link { get; set; }

	[Required]
	[StringLength(300)]
	[Unicode(false)]
	public string Image { get; set; }

	public LanguageEnum Language { get; set; }

	public bool Landscape { get; set; }
}
