// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.EntityFrameworkCore;

using Moonglade.Utils;

namespace Moonglade.Data.Entities;

/// <summary>
/// My Mandates
/// </summary>
public partial class MandateEntity
{
	[Key]
	public int Id { get; set; }

	[Required]
	[StringLength(150)]
	[Unicode(false)]
	public string Link { get; set; }

	[Required]
	[StringLength(150)]
	[Unicode(false)]
	public string Organization { get; set; }

	[StringLength(150)]
	[Unicode(false)]
	public string Summary { get; set; }

	[Required]
	[StringLength(50)]
	[Unicode(false)]
	public string Years { get; set; }

	public LanguageEnum Language { get; set; }
}
