// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.EntityFrameworkCore;

using Moonglade.Utils;

namespace Moonglade.Data.Entities;

/// <summary>
/// Table for Memberships
/// </summary>
public partial class MembershipEntity
{
	[Key]
	public int Id { get; set; }

	[Required]
	[StringLength(100)]
	[Unicode(false)]
	public string Link { get; set; }

	[Required]
	[StringLength(150)]
	[Unicode(false)]
	public string Organzation { get; set; }

	[Required]
	[StringLength(200)]
	[Unicode(false)]
	public string Summary { get; set; }

	public bool Active { get; set; }

	public LanguageEnum Language { get; set; }
}
