// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Moonglade.Data.Entities;

/// <summary>
/// Table with my Projects
/// </summary>
public partial class ProjectEntity
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(150)]
    [Unicode(false)]
    public string PortfolioLink { get; set; }

    [StringLength(150)]
    [Unicode(false)]
    public string ProjectLink { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string ProjectName { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string ProjectSummary { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Client { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Completion { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ProjectType { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Authors { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Language { get; set; }
}