// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.EntityFrameworkCore;

using Moonglade.Utils;

namespace Moonglade.Data.Entities;

/// <summary>
/// My Publications
/// </summary>
public partial class PublicationEntity
{
	[Key]
	public int Id { get; set; }

	[Required]
	[StringLength(100)]
	[Unicode(false)]
	public string PublicationName { get; set; }

	[Required]
	[StringLength(50)]
	[Unicode(false)]
	public string Publisher { get; set; }

	[Column(TypeName = "datetime")]
	public DateTime DatePublished { get; set; }

	[Required]
	[StringLength(100)]
	[Unicode(false)]
	public string Authors { get; set; }

	public bool IsBook { get; set; }

	[Required]
	[StringLength(100)]
	[Unicode(false)]
	public string Title { get; set; }

	[Required]
	[StringLength(150)]
	[Unicode(false)]
	public string Link { get; set; }

	[StringLength(50)]
	[Unicode(false)]
	public string Identifier { get; set; }

	public LanguageEnum Language { get; set; }
}
