// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.EntityFrameworkCore;

using Moonglade.Data.Enums;
using Moonglade.Utils;

namespace Moonglade.Data.Entities;

/// <summary>
/// Table of my held talks
/// </summary>
public partial class TalkEntity
{
	[Key]
	public int Id { get; set; }

	[Required]
	[StringLength(150)]
	[Unicode(false)]
	public string Title { get; set; }

	[Required]
	[StringLength(50)]
	[Unicode(false)]
	public string Where { get; set; }

	[Required]
	[StringLength(150)]
	[Unicode(false)]
	public string Link { get; set; }

	[Required]
	[StringLength(150)]
	[Unicode(false)]
	public string Summary { get; set; }

	public TalkType TalkType { get; set; }

	[Column(TypeName = "datetime")]
	public DateTime Date { get; set; }

	public LanguageEnum Language { get; set; }
}
