// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.EntityFrameworkCore;

using Moonglade.Utils;

namespace Moonglade.Data.Entities;

/// <summary>
/// My Testimonials
/// </summary>
public partial class TestimonialEntity
{
	[Key]
	public int Id { get; set; }

	[StringLength(150)]
	[Unicode(false)]
	public string Link { get; set; }

	[Required]
	[StringLength(600)]
	[Unicode(false)]
	public string Summary { get; set; }

	[Required]
	[StringLength(50)]
	[Unicode(false)]
	public string Recommender { get; set; }

	[Required]
	[StringLength(50)]
	[Unicode(false)]
	public string RecommenderJob { get; set; }

	[Required]
	[StringLength(50)]
	[Unicode(false)]
	public string RecommenderLocation { get; set; }

	[Required]
	[StringLength(50)]
	[Unicode(false)]
	public string Relationship { get; set; }

	[Required]
	[StringLength(150)]
	[Unicode(false)]
	public string ImagePath { get; set; }

	[Column(TypeName = "datetime")]
	public DateTime Date { get; set; }

	public LanguageEnum Language { get; set; }
}
