// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using Microsoft.EntityFrameworkCore;

using Moonglade.Data.Enums;
using Moonglade.Utils;

namespace Moonglade.Data.Entities;

/// <summary>
/// Table of my Videos
/// </summary>
public partial class VideoEntity
{
	[Key]
	public int Id { get; set; }

	[StringLength(150)]
	[Unicode(false)]
	public string Title { get; set; }

	[StringLength(150)]
	[Unicode(false)]
	public string Description { get; set; }

	public VideoType VideoType { get; set; }

	[StringLength(20)]
	[Unicode(false)]
	public string VideoCode { get; set; }

	[Column(TypeName = "datetime")]
	public DateTime? DatePublished { get; set; }

	public LanguageEnum? Language { get; set; }
}
